apiVersion: apps/v1
kind: Deployment
metadata:
  name: siembol-config-editor-ui
spec:
  template:
    spec:
      containers:
      - name: siembol-config-editor-ui
        env:
        - name: TEST_ENV_VARIABLE
          value: "This-is-working-DEVELOPMENT"
