{{- if .Values.ui.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ui.appName }}
  namespace: {{ .Values.namespace }}
  annotations:
    cert-manager.io/issuer: ca-issuer
spec:
  {{ if .Values.tls.enabled -}}
  tls:
  - hosts: 
    - {{ .Values.ui.ingress.hostname }}
    secretName: {{ .Values.ui.appName }}-tls
  {{ end }}
  rules:
  - host: {{ .Values.ui.ingress.hostname }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.ui.appName }}
            port: 
              number: {{ .Values.ui.service.port }}
{{- end -}}